### PR TITLE
chore: update marksman to version 2023-04-12

### PR DESCRIPTION
**Pull request by jfcherng**
- https://github.com/artempyanykh/marksman/releases/tag/2023-04-06
- https://github.com/artempyanykh/marksman/releases/tag/2023-04-12

### CODE REVIEW

**Comment by rchl** [comment]
See https://github.com/artempyanykh/marksman/pull/184
I would default to partial unless we have any known issues with that.

**Comment by rchl** [comment]
@artempyanykh Is configuring server through `initializeOptions` something you have considered?

**Comment by artempyanykh** [comment]
@rchl yes, I can do that. If you have any preferences on the format please case your vote in https://github.com/artempyanykh/marksman/issues/187

Otherwise, it'd be something like 
```
"initializationOptions": {
  "preferredTextSyncKind": 1 | 2 <Full|Incremental>
}
```

**Comment by jfcherng** [comment]
I think this PR has been done.

**Review by predragnikolic — APPROVED** [review]

**Pull request merged**
